#!/usr/bin/env python

# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Flow Matching Policy configuration.

Implements Conditional Flow Matching (Lipman et al., 2023) for robot policy learning,
using the same observation encoding pattern as Diffusion Policy (images + state)
and a 1D UNet backbone for velocity prediction. The integration direction is compatible
with PI05 / RTC (t: 1 → 0).
"""

from dataclasses import dataclass, field

from lerobot.configs.policies import PreTrainedConfig
from lerobot.configs.types import NormalizationMode
from lerobot.optim.optimizers import AdamConfig
from lerobot.optim.schedulers import DiffuserSchedulerConfig
from lerobot.policies.rtc.configuration_rtc import RTCConfig


@PreTrainedConfig.register_subclass("flow_matching")
@dataclass
class FlowMatchingConfig(PreTrainedConfig):
    """Configuration class for FlowMatchingPolicy.

    Defaults are configured for training with PushT providing proprioceptive and single camera observations.

    Notes on the inputs and outputs:
        - "observation.state" is required as an input key.
        - Either:
            - At least one key starting with "observation.image" is required as an input.
              AND/OR
            - The key "observation.environment_state" is required as input.
        - "action" is required as an output key.

    Args:
        n_obs_steps: Number of environment steps worth of observations to pass to the policy.
        horizon: Action prediction horizon (full trajectory length generated by the model).
        n_action_steps: The number of action steps to execute per policy invocation.
        vision_backbone: Name of the torchvision resnet backbone for image encoding.
        crop_shape: (H, W) shape to crop images to. None means no cropping.
        crop_is_random: Whether the crop is random at training time.
        pretrained_backbone_weights: Pretrained weights for the vision backbone. None means random init.
        use_group_norm: Whether to replace BatchNorm with GroupNorm in the backbone.
        spatial_softmax_num_keypoints: Number of keypoints for SpatialSoftmax pooling.
        use_separate_rgb_encoder_per_camera: Whether to use separate encoders per camera.
        down_dims: Feature dimensions for each UNet downsampling stage.
        kernel_size: Convolutional kernel size in the UNet.
        n_groups: Number of groups for GroupNorm in UNet conv blocks.
        time_embed_dim: Dimension of the sinusoidal time embedding.
        use_film_scale_modulation: Whether to use FiLM scale modulation in addition to bias.
        num_inference_steps: Number of integration steps for sampling at inference time.
        solver_type: ODE solver type. "euler" for Euler method, "dopri5" for adaptive ODE solver.
        ode_atol: Absolute tolerance for ODE solver (only used when solver_type="dopri5").
        ode_rtol: Relative tolerance for ODE solver (only used when solver_type="dopri5").
        do_mask_loss_for_padding: Whether to mask loss for padded actions.
        rtc_config: Real-Time Chunking configuration. None to disable RTC.
    """

    # Inputs / output structure.
    n_obs_steps: int = 2
    horizon: int = 16
    n_action_steps: int = 8

    normalization_mapping: dict[str, NormalizationMode] = field(
        default_factory=lambda: {
            "VISUAL": NormalizationMode.MEAN_STD,
            "STATE": NormalizationMode.MIN_MAX,
            "ACTION": NormalizationMode.MIN_MAX,
        }
    )

    # The original implementation doesn't sample frames for the last 7 steps,
    # which avoids excessive padding and leads to improved training results.
    drop_n_last_frames: int = 7  # horizon - n_action_steps - n_obs_steps + 1

    # Architecture / modeling.
    # Vision backbone.
    vision_backbone: str = "resnet18"
    crop_shape: tuple[int, int] | None = (84, 84)
    crop_is_random: bool = True
    pretrained_backbone_weights: str | None = None
    use_group_norm: bool = True
    spatial_softmax_num_keypoints: int = 32
    use_separate_rgb_encoder_per_camera: bool = False

    # UNet (velocity prediction network).
    down_dims: tuple[int, ...] = (512, 1024, 2048)
    kernel_size: int = 5
    n_groups: int = 8
    time_embed_dim: int = 128
    use_film_scale_modulation: bool = True

    # Flow Matching parameters.
    num_inference_steps: int = 10  # ILStudio default: 100 steps for Euler
    solver_type: str = "euler"  # "euler" or "dopri5"
    ode_atol: float = 1e-5  # ODE solver absolute tolerance
    ode_rtol: float = 1e-5  # ODE solver relative tolerance

    # Loss computation.
    do_mask_loss_for_padding: bool = False

    # Real-Time Chunking (RTC) configuration.
    rtc_config: RTCConfig | None = None

    # Training presets.
    optimizer_lr: float = 1e-4
    optimizer_betas: tuple = (0.95, 0.999)
    optimizer_eps: float = 1e-8
    optimizer_weight_decay: float = 1e-6
    scheduler_name: str = "cosine"
    scheduler_warmup_steps: int = 500

    def __post_init__(self):
        super().__post_init__()

        if not self.vision_backbone.startswith("resnet"):
            raise ValueError(
                f"`vision_backbone` must be one of the ResNet variants. Got {self.vision_backbone}."
            )

        supported_solvers = ["euler", "dopri5"]
        if self.solver_type not in supported_solvers:
            raise ValueError(
                f"`solver_type` must be one of {supported_solvers}. Got {self.solver_type}."
            )

        if self.solver_type == "dopri5":
            try:
                import torchdiffeq  # noqa: F401
            except ImportError:
                raise ImportError(
                    "torchdiffeq is required for solver_type='dopri5'. "
                    "Install it with: pip install torchdiffeq"
                ) from None

        # Check that the horizon size and U-Net downsampling are compatible.
        downsampling_factor = 2 ** len(self.down_dims)
        if self.horizon % downsampling_factor != 0:
            raise ValueError(
                "The horizon should be an integer multiple of the downsampling factor (which is determined "
                f"by `len(down_dims)`). Got {self.horizon=} and {self.down_dims=}"
            )

    def get_optimizer_preset(self) -> AdamConfig:
        return AdamConfig(
            lr=self.optimizer_lr,
            betas=self.optimizer_betas,
            eps=self.optimizer_eps,
            weight_decay=self.optimizer_weight_decay,
        )

    def get_scheduler_preset(self) -> DiffuserSchedulerConfig:
        return DiffuserSchedulerConfig(
            name=self.scheduler_name,
            num_warmup_steps=self.scheduler_warmup_steps,
        )

    def validate_features(self) -> None:
        if len(self.image_features) == 0 and self.env_state_feature is None:
            raise ValueError("You must provide at least one image or the environment state among the inputs.")

        if self.crop_shape is not None:
            for key, image_ft in self.image_features.items():
                if self.crop_shape[0] > image_ft.shape[1] or self.crop_shape[1] > image_ft.shape[2]:
                    raise ValueError(
                        f"`crop_shape` should fit within the images shapes. Got {self.crop_shape} "
                        f"for `crop_shape` and {image_ft.shape} for "
                        f"`{key}`."
                    )

        # Check that all input images have the same shape.
        if len(self.image_features) > 0:
            first_image_key, first_image_ft = next(iter(self.image_features.items()))
            for key, image_ft in self.image_features.items():
                if image_ft.shape != first_image_ft.shape:
                    raise ValueError(
                        f"`{key}` does not match `{first_image_key}`, but we expect all image shapes to match."
                    )

    @property
    def observation_delta_indices(self) -> list:
        return list(range(1 - self.n_obs_steps, 1))

    @property
    def action_delta_indices(self) -> list:
        return list(range(1 - self.n_obs_steps, 1 - self.n_obs_steps + self.horizon))

    @property
    def reward_delta_indices(self) -> None:
        return None

